services:
  dash_sens_stat:
    image: sn0am/dash_sensor_status:latest
    container_name: dash_sens_stat
    ports: 
      - 9090:9090
    environment:
        # LIBNMS
      - LIBRENMS_API_URL=${LIBRENMS_API_URL}
      - LIBRENMS_API_TOKEN=${LIBRENMS_API_TOKEN}
        # HEALTHCHECKS
      - HEALTHCHECKS_PINGS_API_KEY=${HEALTHCHECKS_PINGS_API_KEY}
      - HEALTHCHECKS_SCRIPTS_API_KEY=${HEALTHCHECKS_SCRIPTS_API_KEY}
        # VPN EXP
      - MULLVAD_ACC_ID=${MULLVAD_ACC_ID}
        # TWILIO SMS
      - TWIL_SMS_ACCOUNT_SID=${TWIL_SMS_ACCOUNT_SID}
      - TWIL_SMS_AUTH_TOKEN=${TWIL_SMS_AUTH_TOKEN}
        # SMTP2GO
      - SMTP_API_KEY=${SMTP_API_KEY}
        # S3 INFO - BACKBLAZE
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_REGION=${S3_REGION}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    restart: unless-stopped