name: docker_image_create_and_deploy

on: [push]

jobs:
    docker_image_create_and_upload:
        runs-on: ubuntu-latest
        steps:
          - name: Check out code
            uses: actions/checkout@v4

          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
          - name: Build and push to Docker Hub
            uses: docker/build-push-action@v5
            with:
                context: .
                push: true
                tags: |
                  ${{ secrets.DOCKERHUB_USERNAME }}/${{ gitea.event.repository.name }}:latest

    ssh_into_system_and_docker_deploy:
        runs-on: ubuntu-latest
        needs: docker_image_create_and_upload
        steps:
          - name: Deploy to server
            uses: appleboy/ssh-action@v1.0.3
            env:
                LIBRENMS_API_URL: ${{ secrets.LIBRENMS_API_URL }}
                LIBRENMS_API_TOKEN: ${{ secrets.LIBRENMS_API_TOKEN }}
                HEALTHCHECKS_PINGS_API_KEY: ${{ secrets.HEALTHCHECKS_PINGS_API_KEY }}
                HEALTHCHECKS_SCRIPTS_API_KEY: ${{ secrets.HEALTHCHECKS_SCRIPTS_API_KEY }}
                MULLVAD_ACC_ID: ${{ secrets.MULLVAD_ACC_ID }}
                TWIL_SMS_ACCOUNT_SID: ${{ secrets.TWIL_SMS_ACCOUNT_SID }}
                TWIL_SMS_AUTH_TOKEN: ${{ secrets.TWIL_SMS_AUTH_TOKEN }}
                SMTP_API_KEY: ${{ secrets.SMTP_API_KEY }}
                S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
                S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
                S3_REGION: ${{ secrets.S3_REGION }}
                S3_ENDPOINT_URL: ${{ secrets.S3_URL }}
                S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
            with:
                host: ${{ secrets.DEPLOY_SSH_HOST }}
                username: ${{ secrets.DEPLOY_SSH_USERNAME }}
                key: ${{ secrets.HL_LOCAL_SSH_KEY }}
                port: 22
                envs: >
                    LIBRENMS_API_URL,LIBRENMS_API_TOKEN,HEALTHCHECKS_PINGS_API_KEY,HEALTHCHECKS_SCRIPTS_API_KEY,
                    MULLVAD_ACC_ID,TWIL_SMS_ACCOUNT_SID,TWIL_SMS_AUTH_TOKEN,SMTP_API_KEY,S3_ACCESS_KEY,
                    S3_SECRET_KEY,S3_REGION,S3_ENDPOINT_URL,S3_BUCKET_NAME
                script: |
                    docker container rm -f dash_sens_stat
                    docker image rm -f ${{ secrets.DOCKERHUB_USERNAME }}/dash_sensor_status
                    rm -rf "$HOME/compose/${{ gitea.event.repository.name }}"
                    mkdir -p "$HOME/compose/${{ gitea.event.repository.name }}"
                    cd "$HOME/compose/${{ gitea.event.repository.name }}"
                    git clone https://${{ gitea.actor }}:${{ secrets.GITRUNNER_REPO_READ_TOKEN }}@git.noot.cc/${{ gitea.actor }}/${{ gitea.event.repository.name }}.git .
                    docker compose up -d
                    cd "$HOME/compose/"
                    rm -rf ./${{ gitea.event.repository.name }}
